import {
  Star as StarsIcon,
  SportsGymnastics as SportsGymnasticsIcon,
  FitnessCenter as FitnessCenterIcon,
  SportsKabaddi as SportsKabaddiIcon,
  AirlineStops as AirlineStopsIcon,
  CropFree as CropFreeIcon,
  Storm as StormIcon,
  School as SchoolIcon,
  Campaign as CampaignIcon,
  EmojiEvents as EmojiEventsIcon,
} from "@mui/icons-material";
import dayjs from "dayjs";
import advancedFormat from "dayjs/plugin/advancedFormat";
import utc from "dayjs/plugin/utc";

dayjs.extend(utc);
dayjs.extend(advancedFormat);

const classes = {
  DauntlessClassesIcon: {
    fontSize: { xs: "4em", md: "6em" },
    padding: "15px",
  },
  DauntlessCampIcon: {
    height: "160px",
    width: "160px",
    scale: 0.8,
  },
  DauntlessCampPoster: {
    height: "100%",
    width: "160px",
    scale: 0.8,
  },
};

export const camps = [
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Spring Break Tumbling Day Camp Week 1",
    color: "#8e43ba",
    date: {
      start: dayjs.utc(new Date("2025-03-10")),
      end: dayjs.utc(new Date("2025-03-12")),
    },
    time: "9:00 am - 12:00 pm",
    place: "Dauntless Athletics",
    cost: { day: 55, week: 150 },
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/27",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Spring Break Tumbling Day Camp Week 2",
    color: "#8e43ba",
    date: {
      start: dayjs.utc(new Date("2025-03-17")),
      end: dayjs.utc(new Date("2025-03-19")),
    },
    time: "9:00 am - 12:00 pm",
    place: "Dauntless Athletics",
    cost: { day: 55, week: 150 },
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/27",
  },
  {
    icon: <AirlineStopsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Handspring",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-04-05")),
    time: "2:30 - 3:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <StarsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Tucks and Up",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-04-05")),
    time: "3:30 - 4:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <SportsGymnasticsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Aerial",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-04-05")),
    time: "4:30 - 5:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "April Tumbling Camp",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-04-06")),
    time: "1:00 - 4:00 pm",
    place: "Dauntless Athletics",
    cost: 69,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/1",
  },
  {
    icon: <AirlineStopsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Handspring",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-05-17")),
    time: "2:30 - 3:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <StarsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Tucks and Up",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-05-17")),
    time: "3:30 - 4:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <SportsGymnasticsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Aerial",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-05-17")),
    time: "4:30 - 5:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "May Tumbling Camp",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-05-18")),
    time: "1:00 - 4:00 pm",
    place: "Dauntless Athletics",
    cost: 69,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/1",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "June Summer Camp",
    color: "#f01313",
    date: {
      start: dayjs.utc(new Date("2025-06-23")),
      end: dayjs.utc(new Date("2025-06-25")),
    },
    time: "9:00 am - 12:00 pm",
    place: "Dauntless Athletics",
    cost: { day: 55, week: 150 },
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/28",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "July Summer Camp",
    color: "#8e43ba",
    date: {
      start: dayjs.utc(new Date("2025-07-07")),
      end: dayjs.utc(new Date("2025-07-09")),
    },
    time: "9:00 am - 12:00 pm",
    place: "Dauntless Athletics",
    cost: { day: 55, week: 150 },
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/28",
  },
  {
    icon: <StarsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Dauntless Tumbling Camp at Hawaii All Stars - Tucson: Level 1-2",
    color: "#8e43ba",
    date: dayjs.utc(new Date("2025-07-11")),
    time: "10:00 - 11:30 am",
    place: <a href="https://www.hiallstarcheer.com/contact-1">Hawaii All Stars Tucson</a>,
    cost: 60,
    buttonText: "Register For Camp",
    link: "https://portal.iclasspro.com/dauntlessathletics/camps/30",
  },
  {
    icon: <StarsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Dauntless Tumbling Camp at Hawaii All Stars - Tucson: Level 3+",
    color: "#8e43ba",
    date: dayjs.utc(new Date("2025-07-11")),
    time: "11:30 - 1:00 pm",
    place: <a href="https://www.hiallstarcheer.com/contact-1">Hawaii All Stars Tucson</a>,
    cost: 60,
    buttonText: "Register For Camp",
    link: "https://portal.iclasspro.com/dauntlessathletics/camps/32",
  },
  {
    icon: <CampaignIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Matt Kelley Clinic - Back Tuck",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-08-16")),
    time: "2:30 - 4:00 pm",
    place: "Dauntless Athletics",
    cost: 120,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/33",
  },
  {
    icon: <CampaignIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Matt Kelley Clinic - Layout",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-08-16")),
    time: "4:00 - 5:30 pm",
    place: "Dauntless Athletics",
    cost: 120,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/33",
  },
  {
    icon: <CampaignIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Matt Kelley Clinic - Elite",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-08-16")),
    time: "5:30 - 7:00 pm",
    place: "Dauntless Athletics",
    cost: 120,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/33",
  },
  {
    icon: <AirlineStopsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Handspring",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-08-30")),
    time: "2:30 - 3:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <StarsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Tucks and Up",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-08-30")),
    time: "3:30 - 4:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <SportsGymnasticsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Aerial",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-08-30")),
    time: "4:30 - 5:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "August Tumbling Camp",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-08-31")),
    time: "1:00 - 4:00 pm",
    place: "Dauntless Athletics",
    cost: 69,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/1",
  },
  {
    icon: <AirlineStopsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Handspring",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-09-27")),
    time: "2:30 - 3:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <StarsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Back Tucks and Up",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-09-27")),
    time: "3:30 - 4:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <SportsGymnasticsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Focused Tumbling Clinic Aerial",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-09-27")),
    time: "4:30 - 5:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "September Tumbling Camp",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-09-28")),
    time: "1:00 - 4:00 pm",
    place: "Dauntless Athletics",
    cost: 69,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/1",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Fall Break Camp\nWeek 1",
    color: "#8e43ba",
    date: {
      start: dayjs.utc(new Date("2025-09-29")),
      end: dayjs.utc(new Date("2025-10-01")),
    },
    time: "9:00 am - 12:00 pm",
    place: "Dauntless Athletics",
    cost: { day: 55, week: 150 },
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/26",
  },
  {
    icon: <EmojiEventsIcon sx={{ ...classes.DauntlessCampIcon }} />,
    title: "Fall Break Camp\nWeek 2",
    color: "#8e43ba",
    date: {
      start: dayjs.utc(new Date("2025-10-06")),
      end: dayjs.utc(new Date("2025-10-08")),
    },
    time: "9:00 am - 12:00 pm",
    place: "Dauntless Athletics",
    cost: { day: 55, week: 150 },
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/26",
  },
  {
    icon: <img src="/images/camps/silhouette_coed_stunt.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '50%', }} />,
    title: "Fearless Flight Crew Clinic",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-10-12")),
    time: "12:00 - 1:30 pm",
    place: "Dauntless Athletics",
    cost: 150,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/34",
  },
  {
    icon: <img src="/images/camps/silhouette_skeleton_toe_touch.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '50%', }} />,
    title: "October Tumbling Camp",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-10-19")),
    time: "1:00 - 4:00 pm",
    place: "Dauntless Athletics",
    cost: 69,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/1",
  },
  {
    icon: <img src="/images/camps/silhouette_backhandspring.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '15%', }} />,
    title: "Focused Tumbling Clinic Back Handspring",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-10-25")),
    time: "2:30 - 3:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <img src="/images/camps/silhouette_back_tuck.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '50%', }} />,
    title: "Focused Tumbling Clinic Back Tucks and Up",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-10-25")),
    time: "3:30 - 4:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <img src="/images/camps/silhouette_aerial_cartwheel.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '50%', }} />,
    title: "Focused Tumbling Clinic Aerial",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-10-25")),
    time: "4:30 - 5:30 pm",
    place: "Dauntless Athletics",
    cost: 25,
    buttonText: "Register For Clinic",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/18",
  },
  {
    icon: <img src="/images/camps/silhouette_daddy_daughter_clinic.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '50%', }} />,
    title: "Daddy Daughter Clinic",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-10-26")),
    time: "2:00 - 3:30 pm",
    place: "Dauntless Athletics",
    cost: 50,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/36",
  },
  {
    icon: <img src="/images/camps/silhouette_group_stunting.png" style={{ ...classes.DauntlessCampIcon, borderRadius: '50%', }} />,
    title: "All Girl High School Stunt Clinic (must bring entire stunt group)",
    color: "#065E99",
    date: dayjs.utc(new Date("2025-11-02")),
    time: "1:00 - 3:00 pm",
    place: "Dauntless Athletics",
    cost: 30,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/35",
  },
  {
    poster: <img src="/images/camps/adult_clinic.png" style={{ ...classes.DauntlessCampPoster, borderRadius: '15%', }} />,
    title: "Adult Clinic\nAges 19 & up",
    color: "#f01313",
    date: dayjs.utc(new Date("2025-11-09")),
    time: "1:00 - 2:30 pm",
    place: "Dauntless Athletics",
    cost: 15,
    buttonText: "Register For Camp",
    link: "https://app.iclasspro.com/portal/dauntlessathletics/camps/35",
  },
];

export const dauntlessClasses = [
  {
    title: "Tumbling",
    description:
      "We offer every level of tumbling to teach kids basic to advanced tumbling skills. We teach solid fundamentals and spot the kids throughout the skills to ensure their safety and build their confidence. This allows them to acquire skills faster.",
    icon: <AirlineStopsIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(0, 188, 212)" }} />,
  },
  {
    title: "Tumbling Camp",
    description:
      "Let Dauntless Athletics get you ready for your cheer team final selection. Let us help you GET YOUR SKILLS!!",
    icon: (
      <SportsGymnasticsIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(244, 67, 54)" }} />
    ),
  },
  {
    title: "Strength, Conditioning & Flexibility",
    description:
      "We provide circuit style training to help improve the kids' muscular and cardiovascular endurance as well as proper technique for lifting to help build balance and strong muscles.",
    icon: (
      <FitnessCenterIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(255, 144, 105)" }} />
    ),
  },
  {
    title: "Twisting",
    description:
      "We offer an elite tumbling class for athletes who want to learn twisting, combo passes and double flipping skills. The athletes will be spotted repeatedly to help understand the high level skills they will be asked to do.",
    icon: <StormIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(243, 199, 37)" }} />,
  },
  {
    title: "Stunting",
    description:
      "We offer stunting classes for building your skill and dexterity. Basic two-legged stunts, one-legged extended stunts, and high flying basket tosses are only a portion of what we offer.",
    icon: (
      <SportsKabaddiIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(243, 199, 37)" }} />
    ),
  },
  {
    title: "Open Gym",
    description:
      "We offer Open Gym every Monday from 8:30 - 10:30 PM. Bring your friends and have a great time at Dauntless. (*High School and College)",
    icon: <CropFreeIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(184, 255, 0)" }} />,
  },
  {
    title: "High School Onsite Training",
    description:
      "We work with several high school teams across the Valley and offer tumbling on a non-spring tumbling floor. They get more tumbling reps on the same apparatus on which they will compete. Additionally, we use the spring floor to help them gain a better understanding of the skills they are learning. All these techniques help us provide them the most optimal tumbling training.",
    icon: <SchoolIcon sx={{ ...classes.DauntlessClassesIcon, color: "rgb(146, 237, 86)" }} />,
  },
];

export const pricingOptions = [
  {
    title: "1 hour Each Week",
    cost: "$85",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#F44336",
  },
  {
    title: "1.5 hours Each Week",
    cost: "$110",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#3a3a3a",
  },
  {
    title: "2 hours Each Week",
    cost: "$130",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#F44336",
  },
  {
    title: "2.5 hours Each Week",
    cost: "$140",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#3a3a3a",
  },
  {
    title: "3 hours Each Week",
    cost: "$150",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#F44336",
  },
  {
    title: "3.5 hours Each Week",
    cost: "$160",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#3a3a3a",
  },
  {
    title: "4 hours Each Week",
    cost: "$170",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#F44336",
  },
  {
    title: "4.5 hours Each Week",
    cost: "$180",
    duration: "Per Month",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#3a3a3a",
  },
  {
    title: "Private Lessons",
    cost: "Varies",
    duration: "Call for Pricing",
    buttonText: "(480) 214-3908",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#F44336",
    optionalTextList: ["Prices vary by coach"],
  },
  {
    title: "Drop-In Rate",
    cost: "Varies",
    duration: "1 - 1.5 Hours",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/classes",
    backgroundColor: "#3a3a3a",
    optionalTextList: ["$35 for 1 hour single class", "$45 for 1.5 hour single class"],
  },
  {
    title: "Tumbling Camp",
    cost: "$69",
    duration: "3 Hours",
    buttonText: "Schedule Now",
    buttonLink: "https://www.iclassprov2.com/parentportal/dauntlessathletics/camps?camptype=1",
    backgroundColor: "#F44336",
    optionalTextList: ["Beginner", "Intermediate", "Advanced", "*Price is per athlete"],
  },
];
